# Generated by Django 5.0.4 on 2024-05-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_title_84ff5f_idx',
            old_name='blog_post_title_2fcb55_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
